[package]
name = "opentelemetry-stackdriver"
version = "0.7.0"
description = "A Rust opentelemetry exporter that uploads traces to Google Stackdriver trace."
documentation = "https://vivint-smarthome.github.io/opentelemetry-stackdriver/opentelemetry_stackdriver/"
repository = "https://github.com/vivint-smarthome/opentelemetry-stackdriver"
license = "MIT/Apache-2.0"
authors = ["jacobkiesel <jacob.kiesel@vivint.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tonic-build = "0.3.1"
which = "4.0.2"

[dev-dependencies]
futures = { version = "0.3", features = ["thread-pool"] }
tokio = { version = "0.2", features = ["rt-core", "rt-threaded"] }
tracing = "0.1"
tracing-futures = "0.2.2"

[dependencies]
async-trait = "0.1.41"
tracing-opentelemetry = "0.9"
tracing-subscriber = { version = "0.2.15", features = ["ansi"] }
futures = "0.3"
gcp_auth = { version = "0.3.2", optional = true }
hex = "0.4"
http = "0.2"
hyper = "0.13"
hyper-rustls = { version = "0.20", optional = true }
log = "0.4"
opentelemetry = "0.10"
prost = "0.6"
prost-types = "0.6"
rustls = "0.18"
tonic = { version = "0.3.1", features = ["transport", "tls"] }
tokio = { version = "0.2", optional = true }
yup-oauth2 = { version = "4.1", optional = true }
webpki-roots = "0.20"

[features]
default = ["yup-authorizer"]
yup-authorizer = ["hyper-rustls", "yup-oauth2"]
tokio_adapter = ["tokio"]
